server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Puneeths567/spring-app-config
          clone-on-start: true


eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    regsiter-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
